# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MeetingCalendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeetingCalendar
    pod 'Alamofire', '~> 4.4'
    pod 'PSTAlertController'

  target 'MeetingCalendarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeetingCalendarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
